Workflow updates

diff --git a/.github/workflows/gcp.yml b/.github/workflows/gcp.yml
--- a/.github/workflows/gcp.yml
+++ b/.github/workflows/gcp.yml
@@ -76,45 +76,53 @@ jobs:
     # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
     - name: Terraform Plan
       id: tf-plan
-      # run: terraform plan -input=false
-      run: |
-        export exitcode=0
-        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+      run: terraform plan -input=false
+    #   run: |
+    #     export exitcode=0
+    #     terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
 
-        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+    #     echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
         
-        if [ $exitcode -eq 1 ]; then
-          echo Terraform Plan Failed!
-          exit 1
-        else 
-          exit 0
-        fi
+    #     if [ $exitcode -eq 1 ]; then
+    #       echo Terraform Plan Failed!
+    #       exit 1
+    #     else 
+    #       exit 0
+    #     fi
       
-    # Create string output of Terraform Plan
-    - name: Create String Output
-      id: tf-plan-string
-      run: |
-        TERRAFORM_PLAN=$(terraform show -no-color tfplan)
-        
-        delimiter="$(openssl rand -hex 8)"
-        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
-        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
-        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
-        echo "" >> $GITHUB_OUTPUT
-        echo '```terraform' >> $GITHUB_OUTPUT
-        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
-        echo '```' >> $GITHUB_OUTPUT
-        echo "</details>" >> $GITHUB_OUTPUT
-        echo "${delimiter}" >> $GITHUB_OUTPUT
-    # Publish Terraform Plan as task summary
-    - name: Publish Terraform Plan to Task Summary
-      env:
-        SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
-      run: |
-        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+    # # Save plan to artifacts  
+    # - name: Publish Terraform Plan
+    #   uses: actions/upload-artifact@v3
+    #   with:
+    #     name: tfplan
+    #     path: tfplan
 
-      # On push to "main", build or change infrastructure according to Terraform configuration files
-      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
+    # # Create string output of Terraform Plan
+    # - name: Create String Output
+    #   id: tf-plan-string
+    #   run: |
+    #     TERRAFORM_PLAN=$(terraform show -no-color tfplan)
+        
+    #     delimiter="$(openssl rand -hex 8)"
+    #     echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+    #     echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+    #     echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+    #     echo "" >> $GITHUB_OUTPUT
+    #     echo '```terraform' >> $GITHUB_OUTPUT
+    #     echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
+    #     echo '```' >> $GITHUB_OUTPUT
+    #     echo "</details>" >> $GITHUB_OUTPUT
+    #     echo "${delimiter}" >> $GITHUB_OUTPUT
+
+    # # Publish Terraform Plan as task summary
+    # - name: Publish Terraform Plan to Task Summary
+    #   env:
+    #     SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
+    #   run: |
+    #     echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+
+    # On push to "main", build or change infrastructure according to Terraform configuration files
+    # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
     - name: Terraform Apply
       if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
       run: terraform apply -auto-approve -input=false
