Workflow tf plan step updated

diff --git a/.github/workflows/gcp.yml b/.github/workflows/gcp.yml
--- a/.github/workflows/gcp.yml
+++ b/.github/workflows/gcp.yml
@@ -73,8 +73,22 @@ jobs:
       run: terraform fmt -check
 
     # Generates an execution plan for Terraform
+    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
     - name: Terraform Plan
-      run: terraform plan -input=false
+      id: tf-plan
+      # run: terraform plan -input=false
+      run: |
+        export exitcode=0
+        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+
+        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+        
+        if [ $exitcode -eq 1 ]; then
+          echo Terraform Plan Failed!
+          exit 1
+        else 
+          exit 0
+        fi
 
       # On push to "main", build or change infrastructure according to Terraform configuration files
       # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
